import React, { Component } from "react";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import User from "../layouts/User";

export default class Home extends Component {
  constructor(props) {
    super(props);
    this.state = {
      modal: false,
      username: "",
      password: "",
    };
  }
  
  _updateField = (field) => (e) => this.setState({ [field]: e.target.value });
  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div> hello home</div>
      </div>
    );
  }
}
Home.getLayout = function getLayout(page) {
  return <User>{page}</User>;
};
