import React, { Component } from "react";
import Head from "next/head";
import Link from "next/link";

import styles from "../styles/Home.module.css";
import User from "../layouts/User";
import Banner from "../containers/Banner";

export default class Home extends Component {
  constructor(props) {
    super(props);
    this.state = {
      modal: false,
      username: "",
      password: "",
    };
  }

  _updateField = (field) => (e) => this.setState({ [field]: e.target.value });
  render() {
    return (
      <>
        <Head>
          <title>Cửa hàng trái cây</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Banner />
        <div className="container my-5">
          <h1 className="text-center mb-5">Các sản phẩm của cửa hàng</h1>
          <div className="row">
            <div className="col-4 mb-4">
              <div id="card-pr" className="card h-100">
                <div className="w-100" style={{ height: "300px" }}>
                  <img
                    src="/static/images/bo.jpg"
                    className="card-img-top"
                    alt="..."
                    style={{ height: "100%" }}
                  />
                </div>

                <div className="card-body text-center">
                  <span className="card-text text-secondary fw-light">Bơ</span>
                  <p className="card-text fw-bolder fs-4">Bơ campuchia</p>
                  <div
                    id="add-cart"
                    href="#"
                    className="p-3 bg-warning position-absolute top-50 start-50 d-flex align-items-center"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="icon icon-tabler icon-tabler-shopping-cart me-2"
                      width={24}
                      height={24}
                      viewBox="0 0 24 24"
                      strokeWidth="1.5"
                      stroke="#2c3e50"
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                      <circle cx={6} cy={19} r={2} />
                      <circle cx={17} cy={19} r={2} />
                      <path d="M17 17h-11v-14h-2" />
                      <path d="M6 5l14 1l-1 7h-13" />
                    </svg>
                    Thêm vào giỏ hàng
                  </div>
                </div>
              </div>
            </div>
            <div className="col-4 mb-4">
              <div id="card-pr" className="card h-100">
                <div className="w-100" style={{ height: "300px" }}>
                  <img
                    src="/static/images/dudu.jpg"
                    className="card-img-top"
                    alt="..."
                    style={{ height: "100%" }}
                  />
                </div>

                <div className="card-body text-center">
                  <span className="card-text text-secondary fw-light">Bơ</span>
                  <p className="card-text fw-bolder fs-4">Bơ campuchia</p>
                  <div
                    id="add-cart"
                    href="#"
                    className="p-3 bg-warning position-absolute top-50 start-50 d-flex align-items-center"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="icon icon-tabler icon-tabler-shopping-cart me-2"
                      width={24}
                      height={24}
                      viewBox="0 0 24 24"
                      strokeWidth="1.5"
                      stroke="#2c3e50"
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                      <circle cx={6} cy={19} r={2} />
                      <circle cx={17} cy={19} r={2} />
                      <path d="M17 17h-11v-14h-2" />
                      <path d="M6 5l14 1l-1 7h-13" />
                    </svg>
                    Thêm vào giỏ hàng
                  </div>
                </div>
              </div>
            </div>
            <div className="col-4 mb-4">
              <div id="card-pr" className="card h-100">
                <div className="w-100" style={{ height: "300px" }}>
                  <img
                    src="/static/images/dau-tay.jpg"
                    className="card-img-top"
                    alt="..."
                    style={{ height: "100%" }}
                  />
                </div>

                <div className="card-body text-center">
                  <span className="card-text text-secondary fw-light">Bơ</span>
                  <p className="card-text fw-bolder fs-4">Bơ campuchia</p>
                  <div
                    id="add-cart"
                    href="#"
                    className="p-3 bg-warning position-absolute top-50 start-50 d-flex align-items-center"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="icon icon-tabler icon-tabler-shopping-cart me-2"
                      width={24}
                      height={24}
                      viewBox="0 0 24 24"
                      strokeWidth="1.5"
                      stroke="#2c3e50"
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                      <circle cx={6} cy={19} r={2} />
                      <circle cx={17} cy={19} r={2} />
                      <path d="M17 17h-11v-14h-2" />
                      <path d="M6 5l14 1l-1 7h-13" />
                    </svg>
                    Thêm vào giỏ hàng
                  </div>
                </div>
              </div>
            </div>
            <div className="col-4 mb-4">
              <div id="card-pr" className="card h-100">
                <div className="w-100" style={{ height: "300px" }}>
                  <img
                    src="/static/images/mit.jpg"
                    className="card-img-top"
                    alt="..."
                    style={{ height: "100%" }}
                  />
                </div>

                <div className="card-body text-center">
                  <span className="card-text text-secondary fw-light">Bơ</span>
                  <p className="card-text fw-bolder fs-4">Bơ campuchia</p>
                  <div
                    id="add-cart"
                    href="#"
                    className="p-3 bg-warning position-absolute top-50 start-50 d-flex align-items-center"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="icon icon-tabler icon-tabler-shopping-cart me-2"
                      width={24}
                      height={24}
                      viewBox="0 0 24 24"
                      strokeWidth="1.5"
                      stroke="#2c3e50"
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                      <circle cx={6} cy={19} r={2} />
                      <circle cx={17} cy={19} r={2} />
                      <path d="M17 17h-11v-14h-2" />
                      <path d="M6 5l14 1l-1 7h-13" />
                    </svg>
                    Thêm vào giỏ hàng
                  </div>
                </div>
              </div>
            </div>
            <div className="col-4 mb-4">
              <div id="card-pr" className="card h-100">
                <div className="w-100" style={{ height: "300px" }}>
                  <img
                    src="/static/images/nho1.jpg"
                    className="card-img-top"
                    alt="..."
                    style={{ height: "100%" }}
                  />
                </div>

                <div className="card-body text-center">
                  <span className="card-text text-secondary fw-light">Bơ</span>
                  <p className="card-text fw-bolder fs-4">Bơ campuchia</p>
                  <div
                    id="add-cart"
                    href="#"
                    className="p-3 bg-warning position-absolute top-50 start-50 d-flex align-items-center"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="icon icon-tabler icon-tabler-shopping-cart me-2"
                      width={24}
                      height={24}
                      viewBox="0 0 24 24"
                      strokeWidth="1.5"
                      stroke="#2c3e50"
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                      <circle cx={6} cy={19} r={2} />
                      <circle cx={17} cy={19} r={2} />
                      <path d="M17 17h-11v-14h-2" />
                      <path d="M6 5l14 1l-1 7h-13" />
                    </svg>
                    Thêm vào giỏ hàng
                  </div>
                </div>
              </div>
            </div>
            <div className="col-4 mb-4">
              <div id="card-pr" className="card h-100">
                <div className="w-100" style={{ height: "300px" }}>
                  <img
                    src="/static/images/viet_quat.jpg"
                    className="card-img-top"
                    alt="..."
                    style={{ height: "100%" }}
                  />
                </div>

                <div className="card-body text-center">
                  <span className="card-text text-secondary fw-light">Bơ</span>
                  <p className="card-text fw-bolder fs-4">Bơ campuchia</p>
                  <div
                    id="add-cart"
                    href="#"
                    className="p-3 bg-warning position-absolute top-50 start-50 d-flex align-items-center"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="icon icon-tabler icon-tabler-shopping-cart me-2"
                      width={24}
                      height={24}
                      viewBox="0 0 24 24"
                      strokeWidth="1.5"
                      stroke="#2c3e50"
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                      <circle cx={6} cy={19} r={2} />
                      <circle cx={17} cy={19} r={2} />
                      <path d="M17 17h-11v-14h-2" />
                      <path d="M6 5l14 1l-1 7h-13" />
                    </svg>
                    Thêm vào giỏ hàng
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="d-flex justify-content-center">
            <Link href="/product">
              <a
                id="read-more"
                className="py-3 px-5 bg-warning d-inline rounded-pill"
                style={{ cursor: "pointer" }}
                href="#"
              >
                Xem thêm
              </a>
            </Link>
          </div>
        </div>
      </>
    );
  }
}
Home.getLayout = function getLayout(page) {
  return <User>{page}</User>;
};
