import React, { Component } from "react";
import Head from "next/head";

import User from "../../layouts/User";
import Link from "next/link"
import BannerProduct from "../../containers/BannerProduct";
export default class Product extends Component {
  constructor(props) {
    super(props);
    this.state = {
      count:0,
      
    };
  }

  _updateField = (field) => (e) => this.setState({ [field]: e.target.value });

  render() {
    console.log('state',this.state);
    return (
      <>
        <Head>
          <title>Cửa hàng trái cây</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <BannerProduct />
        <div className="container my-5">
          <div className="row">
            <div className="col-9">
              <div className="row">
                <div className="col-4 mb-4">
                 
                  <div id="card-pr" className="card h-100">
                    <div className="w-100" style={{ height: "300px" }}>
                      <img
                        src="/static/images/bo.jpg"
                        className="card-img-top"
                        alt="..."
                        style={{ height: "100%" }}
                      />
                    </div>

                    <div className="card-body text-center">
                      <span className="card-text text-secondary fw-light">
                        Bơ
                      </span>
                      <p className="card-text fw-bolder fs-4">Bơ campuchia</p>
                      <Link href="/product-detail?id=1">
                        <a href="#">Xem chi tiết</a>
                      </Link>
                      <div
                        id="add-cart"
                        href="#"
                        className="p-3 bg-warning position-absolute top-50 start-50 d-flex align-items-center"
                        onClick={()=>this.setState({count:this.state.count + 1})}
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className="icon icon-tabler icon-tabler-shopping-cart me-2"
                          width={40}
                          height={40}
                          viewBox="0 0 24 24"
                          strokeWidth="1.5"
                          stroke="#2c3e50"
                          fill="none"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                          <circle cx={6} cy={19} r={2} />
                          <circle cx={17} cy={19} r={2} />
                          <path d="M17 17h-11v-14h-2" />
                          <path d="M6 5l14 1l-1 7h-13" />
                        </svg>
                        Thêm vào giỏ hàng
                      </div>
                    </div>
                  </div>
                
                  
                </div>
                <div className="col-4 mb-4">
                  <div id="card-pr" className="card h-100">
                    <div className="w-100" style={{ height: "300px" }}>
                      <img
                        src="/static/images/dudu.jpg"
                        className="card-img-top"
                        alt="..."
                        style={{ height: "100%" }}
                      />
                    </div>

                    <div className="card-body text-center">
                      <span className="card-text text-secondary fw-light">
                        Bơ
                      </span>
                      <p className="card-text fw-bolder fs-4">Bơ campuchia</p>
                      <div
                        id="add-cart"
                        href="#"
                        className="p-3 bg-warning position-absolute top-50 start-50 d-flex align-items-center"
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className="icon icon-tabler icon-tabler-shopping-cart me-2"
                          width={24}
                          height={24}
                          viewBox="0 0 24 24"
                          strokeWidth="1.5"
                          stroke="#2c3e50"
                          fill="none"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                          <circle cx={6} cy={19} r={2} />
                          <circle cx={17} cy={19} r={2} />
                          <path d="M17 17h-11v-14h-2" />
                          <path d="M6 5l14 1l-1 7h-13" />
                        </svg>
                        Thêm vào giỏ hàng
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-4 mb-4">
                  <div id="card-pr" className="card h-100">
                    <div className="w-100" style={{ height: "300px" }}>
                      <img
                        src="/static/images/dau-tay.jpg"
                        className="card-img-top"
                        alt="..."
                        style={{ height: "100%" }}
                      />
                    </div>

                    <div className="card-body text-center">
                      <span className="card-text text-secondary fw-light">
                        Bơ
                      </span>
                      <p className="card-text fw-bolder fs-4">Bơ campuchia</p>
                      <div
                        id="add-cart"
                        href="#"
                        className="p-3 bg-warning position-absolute top-50 start-50 d-flex align-items-center"
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className="icon icon-tabler icon-tabler-shopping-cart me-2"
                          width={24}
                          height={24}
                          viewBox="0 0 24 24"
                          strokeWidth="1.5"
                          stroke="#2c3e50"
                          fill="none"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                          <circle cx={6} cy={19} r={2} />
                          <circle cx={17} cy={19} r={2} />
                          <path d="M17 17h-11v-14h-2" />
                          <path d="M6 5l14 1l-1 7h-13" />
                        </svg>
                        Thêm vào giỏ hàng
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-4 mb-4">
                  <div id="card-pr" className="card h-100">
                    <div className="w-100" style={{ height: "300px" }}>
                      <img
                        src="/static/images/mit.jpg"
                        className="card-img-top"
                        alt="..."
                        style={{ height: "100%" }}
                      />
                    </div>

                    <div className="card-body text-center">
                      <span className="card-text text-secondary fw-light">
                        Bơ
                      </span>
                      <p className="card-text fw-bolder fs-4">Bơ campuchia</p>
                      <div
                        id="add-cart"
                        href="#"
                        className="p-3 bg-warning position-absolute top-50 start-50 d-flex align-items-center"
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className="icon icon-tabler icon-tabler-shopping-cart me-2"
                          width={24}
                          height={24}
                          viewBox="0 0 24 24"
                          strokeWidth="1.5"
                          stroke="#2c3e50"
                          fill="none"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                          <circle cx={6} cy={19} r={2} />
                          <circle cx={17} cy={19} r={2} />
                          <path d="M17 17h-11v-14h-2" />
                          <path d="M6 5l14 1l-1 7h-13" />
                        </svg>
                        Thêm vào giỏ hàng
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-4 mb-4">
                  <div id="card-pr" className="card h-100">
                    <div className="w-100" style={{ height: "300px" }}>
                      <img
                        src="/static/images/nho1.jpg"
                        className="card-img-top"
                        alt="..."
                        style={{ height: "100%" }}
                      />
                    </div>

                    <div className="card-body text-center">
                      <span className="card-text text-secondary fw-light">
                        Bơ
                      </span>
                      <p className="card-text fw-bolder fs-4">Bơ campuchia</p>
                      <div
                        id="add-cart"
                        href="#"
                        className="p-3 bg-warning position-absolute top-50 start-50 d-flex align-items-center"
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className="icon icon-tabler icon-tabler-shopping-cart me-2"
                          width={24}
                          height={24}
                          viewBox="0 0 24 24"
                          strokeWidth="1.5"
                          stroke="#2c3e50"
                          fill="none"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                          <circle cx={6} cy={19} r={2} />
                          <circle cx={17} cy={19} r={2} />
                          <path d="M17 17h-11v-14h-2" />
                          <path d="M6 5l14 1l-1 7h-13" />
                        </svg>
                        Thêm vào giỏ hàng
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-4 mb-4">
                  <div id="card-pr" className="card h-100">
                    <div className="w-100" style={{ height: "300px" }}>
                      <img
                        src="/static/images/viet_quat.jpg"
                        className="card-img-top"
                        alt="..."
                        style={{ height: "100%" }}
                      />
                    </div>

                    <div className="card-body text-center">
                      <span className="card-text text-secondary fw-light">
                        Bơ
                      </span>
                      <p className="card-text fw-bolder fs-4">Bơ campuchia</p>
                      <div
                        id="add-cart"
                        href="#"
                        className="p-3 bg-warning position-absolute top-50 start-50 d-flex align-items-center"
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className="icon icon-tabler icon-tabler-shopping-cart me-2"
                          width={24}
                          height={24}
                          viewBox="0 0 24 24"
                          strokeWidth="1.5"
                          stroke="#2c3e50"
                          fill="none"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                          <circle cx={6} cy={19} r={2} />
                          <circle cx={17} cy={19} r={2} />
                          <path d="M17 17h-11v-14h-2" />
                          <path d="M6 5l14 1l-1 7h-13" />
                        </svg>
                        Thêm vào giỏ hàng
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-3">
              <div className="input-group mb-3">
                <input
                  id="ip-search"
                  type="text"
                  className="form-control"
                  placeholder="Nhập loại hoa quả cần tìm"
                  aria-label="Recipient's username"
                  aria-describedby="button-addon2"
                />
                <button
                  className="btn btn-success"
                  type="button"
                  id="button-addon2"
                  style={{ borderColor: "#157347" }}
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="icon icon-tabler icon-tabler-search"
                    width={24}
                    height={24}
                    viewBox="0 0 24 24"
                    strokeWidth="1.5"
                    stroke="#ffffff"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <circle cx={10} cy={10} r={7} />
                    <line x1={21} y1={21} x2={15} y2={15} />
                  </svg>
                </button>
              </div>
              <div className="fs-4">Danh mục trái cây</div>
              <ul style={{ listStyle: "none" }}>
                <li className="py-3">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="icon icon-tabler icon-tabler-arrow-bar-left me-2"
                    width={24}
                    height={24}
                    viewBox="0 0 24 24"
                    strokeWidth="1.5"
                    stroke="#000000"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <line x1={4} y1={12} x2={14} y2={12} />
                    <line x1={4} y1={12} x2={8} y2={16} />
                    <line x1={4} y1={12} x2={8} y2={8} />
                    <line x1={20} y1={4} x2={20} y2={20} />
                  </svg>
                  Cam
                </li>
                <li className="py-3">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="icon icon-tabler icon-tabler-arrow-bar-left me-2"
                    width={24}
                    height={24}
                    viewBox="0 0 24 24"
                    strokeWidth="1.5"
                    stroke="#000000"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <line x1={4} y1={12} x2={14} y2={12} />
                    <line x1={4} y1={12} x2={8} y2={16} />
                    <line x1={4} y1={12} x2={8} y2={8} />
                    <line x1={20} y1={4} x2={20} y2={20} />
                  </svg>
                  Táo
                </li>
                <li className="py-3">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="icon icon-tabler icon-tabler-arrow-bar-left me-2"
                    width={24}
                    height={24}
                    viewBox="0 0 24 24"
                    strokeWidth="1.5"
                    stroke="#000000"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <line x1={4} y1={12} x2={14} y2={12} />
                    <line x1={4} y1={12} x2={8} y2={16} />
                    <line x1={4} y1={12} x2={8} y2={8} />
                    <line x1={20} y1={4} x2={20} y2={20} />
                  </svg>
                  Ổi
                </li>
                <li className="py-3">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="icon icon-tabler icon-tabler-arrow-bar-left me-2"
                    width={24}
                    height={24}
                    viewBox="0 0 24 24"
                    strokeWidth="1.5"
                    stroke="#000000"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <line x1={4} y1={12} x2={14} y2={12} />
                    <line x1={4} y1={12} x2={8} y2={16} />
                    <line x1={4} y1={12} x2={8} y2={8} />
                    <line x1={20} y1={4} x2={20} y2={20} />
                  </svg>
                  Nho
                </li>
                <li className="py-3">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="icon icon-tabler icon-tabler-arrow-bar-left me-2"
                    width={24}
                    height={24}
                    viewBox="0 0 24 24"
                    strokeWidth="1.5"
                    stroke="#000000"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <line x1={4} y1={12} x2={14} y2={12} />
                    <line x1={4} y1={12} x2={8} y2={16} />
                    <line x1={4} y1={12} x2={8} y2={8} />
                    <line x1={20} y1={4} x2={20} y2={20} />
                  </svg>
                  Dưa hấu
                </li>
              </ul>
            </div>
          </div>
        </div>
      </>
    );
  }
}
Product.getLayout = function getLayout(page) {
  return <User>{page}</User>;
};
