spring:
  application:
    name: fruit
  datasource:
    url: jdbc:mysql://localhost:3306/fruit_store?useSSL=false
    username: root
    password: 12345678
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        enable_lazy_load_no_trans: true
        format_sql: create
    show-sql: true

paging:
  default:
    page: 0
    size: 20

jwt:
  secret: keysecret2021
  
logging:
  level:
    org.springframework.cache: error
  file:
    name: logs/socialising
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 100MB
      max-history: 7


feign:
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 1200000
  eager-load:
    enabled: true
    clients: service-bar

otp:
  ExpriedTime: 900

server:
  error:
    include-message: always
  port: 8080
